### ISSUE TITLE
Part list?

### ISSUE THREAD

**Issue by harking** [robprojects/944maf-pcb#1]
Hi! I’m interested in making a kit of these for myself as well as the Vanagon community. It uses, I think, the same 4 pin MAF from my examining of my own Van’s sensor. 

Could you share the parts you used? What VW hot wire MAF did you use?

Thanks!! Super stoked to find your project. A company called GoWesty previously made a similar hot wire MAF but stopped selling it.

**Comment by harking** [comment]
Maybe this? 0281002757

**Comment by robprojects** [comment]
Sorry for the slow reply. I've updated the BOM to make clear the parts that I have used. For the MAF sensor I used one from an Audi A3 S3 TT 1.8 Quattro 1996-2006. You will need to find one that fits the diameter of the intake and adjust the map to suit.

**Comment by harking** [comment]
Awesome! Thank you!

Did you need to adjust the data point map from MAF to AFM at all for controlling the air/fuel mixture in the computer?

The original AFM had an idle mixture adjustment, as well as the ability to slightly calibrate the internal wiper. Not sure if those matter much with your implementation.

**Comment by robprojects** [comment]
The map in the source code works reasonably on a Porsche 944S2 (it will run the engine and drive). The AFM in the Porsche doesn't have an idle screw or any adjustment. I'd plan on making your own map...
